#!/usr/bin/env bash

die () {
  echo "$1"
  exit 1
}

[ -z "${LETSENCRYPT_EMAIL}" ] && die "Please set 'LETSENCRYPT_EMAIL'"
[ -z "${NGINX_CONTAINER}" ] && die "Please set 'NGINX_CONTAINER'"

if [[ ! -f /etc/nginx/certs/dhparam.pem ]]; then
  openssl dhparam -out /etc/nginx/certs/dhparam.pem 2048
fi

touch /output/log
tail -f -n 0 /output/log &
/app/letsencrypt-service &
exec docker-gen \
    -watch \
    -only-exposed \
    -notify '/app/handle-new-spec' \
    /app/spec.tmpl /output/spec
