#!/usr/bin/env bash

source /app/load-spec

TMP_CONF="/output/nginx-tmp.conf"

gen-nginx-conf () {
  echo > "${TMP_CONF}"
  echo '# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
  # scheme used to connect to this server
  map $http_x_forwarded_proto $proxy_x_forwarded_proto {
    default $http_x_forwarded_proto;
    ""      $scheme;
  }

  # If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
  # Connection header that may have been passed to this server
  map $http_upgrade $proxy_connection {
    default upgrade;
    "" close;
  }' >> "${TMP_CONF}"
  nginx-gzip-conf >> "${TMP_CONF}"
  nginx-proxy-conf >> "${TMP_CONF}"
  nginx-server-conf >> "${TMP_CONF}"
}

nginx-server-conf () {
  for host in ${HOSTS[@]}; do
    if [ -f /etc/nginx/vhost.d/${host} ]; then
      if ! grep -q '/.well-known/' /etc/nginx/vhost.d/${host}; then
        echo >> /etc/nginx/vhost.d/${host}
        cat /app/acme-vhost.conf >> /etc/nginx/vhost.d/${host}
      fi
    else
      cp /app/acme-vhost.conf /etc/nginx/vhost.d/${host}
    fi

    echo "upstream $host {
      ${UPSTREAM[$host]}
    }"

    # Get the basename of the certificate
    # Default is default
    CERT_NAME="default"
    # If $host.crt exists, use $host
    if [ -f "/etc/nginx/certs/${host}.crt" ]; then
      CERT_NAME="$host"
    fi
    # If CERT_NAME defined in container env, use that
    if [ -n "${CERT_NAMES[$host]}" ]; then
      CERT_NAME="${CERT_NAMES[$host]}"
    fi

    DEFAULT_SERVER_FLAG=""
    if [ "${host}" == "${DEFAULT_SERVER}" ]; then
      DEFAULT_SERVER_FLAG="default_server"
    fi

    PORT="80"
    SSL_ENABLED=""
    SSL_CONF=""
    SSL_DHPARAM=""
    HTTPS_REDIRECT=""
    if [ -f "/etc/nginx/certs/${CERT_NAME}.crt" ]; then
    #if true; then
      PORT="443 ssl http2"
      SSL_ENABLED="true"
      if [ -f "/etc/nginx/certs/${CERT_NAME}.dhparam.pem" ]; then
        SSL_DHPARAM="ssl_dhparam /etc/nginx/certs/${CERT_NAME}.dhparam.pem;"
      fi
      HTTPS_REDIRECT="# Redirecto to https
      server {
        server_name ${host} ${DEFAULT_SERVER_FLAG};
        listen 80;
        access_log /var/log/nginx/${host}.log;
        return 301 https://\$host\$request_uri;
      }"
      SSL_CONF="ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
      ssl_ciphers $(cat /app/ssl-ciphers);

      ssl_prefer_server_ciphers on;
      ssl_session_timeout 5m;
      ssl_session_cache shared:SSL:50m;

      ssl_certificate /etc/nginx/certs/${CERT_NAME}.crt;
      ssl_certificate_key /etc/nginx/certs/${CERT_NAME}.key;
      ${SSL_DHPARAM}

      add_header Strict-Transport-Security \"max-age=31536000\";"
    fi

    CORS_CONF=""
    if [ "${CORS_ENABLED[$host]}" == "true" ]; then
      CORS_CONF="add_header 'Access-Control-Allow-Credentials' 'true';
      add_header 'Access-Control-Allow-Origin' '${CORS_ORIGIN[$host]:-*}';
      add_header 'Access-Control-Allow-Methods' '${CORS_METHODS[$host]:-GET}';
      add_header 'Access-Control-Allow-Headers' '${CORS_HEADERS[$host]:-Access-Control-Request-Headers,Authorization,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Accept-Encoding}';
      "
    fi

    AUTH_BASIC=""
    if [ -f "/etc/nginx/htpasswd/${host}" ]; then
      AUTH_BASIC="auth_basic \"Restricted ${host}\";
      auth_basic_user_file /etc/nginx/htpasswd/${host};"
    fi

    EXTRA_CONF_SERVER=""
    if [ -f "/etc/nginx/vhost.d/${host}" ]; then
      EXTRA_CONF_SERVER="include /etc/nginx/vhost.d/${host};"
    elif [ -f "/etc/nginx/vhost.d/default" ]; then
      EXTRA_CONF_SERVER="include /etc/nginx/vhost.d/default;"
    fi

    EXTRA_CONF_LOCATION=""
    if [ -f "/etc/nginx/vhost.d/${host}_location" ]; then
      EXTRA_CONF_LOCATION="include /etc/nginx/vhost.d/${host}_location;"
    elif [ -f "/etc/nginx/vhost.d/default_location" ]; then
      EXTRA_CONF_LOCATION="include /etc/nginx/vhost.d/default_location;"
    fi

    echo "${HTTPS_REDIRECT}
    server {
      server_name ${host} ${DEFAULT_SERVER_FLAG};
      listen ${PORT};
      access_log /var/log/nginx/${host}.log;
      ${SSL_CONF}
      ${EXTRA_CONF_SERVER}

      location / {
        proxy_pass http://${host};
        ${CORS_CONF}
        ${AUTH_BASIC}
        ${EXTRA_CONF_LOCATION}
      }
    }"
  done
}

nginx-gzip-conf () {
  if [ ! -f /etc/nginx/conf.d/gzip.conf ]; then
    echo 'gzip on;
    gzip_proxied any;
    gzip_types
        text/plain
        text/css
        text/javascript
        application/javascript
        application/json
        application/x-javascript
        js
        text/xml
        application/xml
        application/rss+xml
        image/svg+xml;
    #gzip_min_length 256;
    gzip_vary on;
    gzip_disable "msie6";
    gzip_comp_level 4;'
  fi
}

nginx-proxy-conf () {
  if [ ! -f /etc/nginx/conf.d/proxy.conf ]; then
    echo '# HTTP 1.1 support
    proxy_http_version 1.1;
    proxy_buffering off;
    proxy_set_header Host $http_host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $proxy_connection;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;'
  fi
}

gen-nginx-conf
