#!/usr/bin/env bash

if [ -f /etc/nginx/certs/wildcard.crt ]; then
  exit
fi

/app/acme.sh \
  --issue \
  --dns dns_aws \
  -d "$LETSENCRYPT_DOMAIN" \
  -d "*.$LETSENCRYPT_DOMAIN" \
  --accountemail "$LETSENCRYPT_EMAIL" \
  --fullchain-file "/etc/nginx/certs/default.crt" \
  --key-file "/etc/nginx/certs/default.key"
