#!/usr/bin/env bash

unset HOSTS
declare -a HOSTS

unset CERT_NAMES
declare -A CERT_NAMES

unset CORS_ENABLED
declare -A CORS_ENABLED

unset CORS_ORIGIN
declare -A CORS_ORIGIN

unset CORS_METHODS
declare -A CORS_METHODS

unset CORS_HEADERS
declare -A CORS_HEADERS

unset UPSTREAM
declare -A UPSTREAM

register-host () {
  HOSTS+=("$1")
}

cert-name () {
  # shellcheck disable=SC2034
  CERT_NAMES["$1"]="$2"
}

cors-enabled () {
  # shellcheck disable=SC2034
  CORS_ENABLED["$1"]="$2"
}

cors-origin () {
  # shellcheck disable=SC2034
  CORS_ORIGIN["$1"]="$2"
}

cors-methods () {
  # shellcheck disable=SC2034
  CORS_METHODS["$1"]="$2"
}

cors-headers () {
  # shellcheck disable=SC2034
  CORS_HEADERS["$1"]="$2"
}

add-upstream () {
  local hostname="$1"
  local containername="$2"
  local ipport="$3"

  UPSTREAM["$hostname"]="${UPSTREAM["$hostname"]}
  # ${containername}
  server ${ipport};"
}

if [ -s /output/spec ]; then
  # shellcheck disable=SC1091
  source /output/spec
fi

if [ -s /output/extra-spec ]; then
  # shellcheck disable=SC1091
  source /output/extra-spec
fi
