#!/usr/bin/env bash

# shellcheck disable=SC1091
source /app/load-spec

ACME_CA_URI=${ACME_CA_URI:-https://acme-v01.api.letsencrypt.org/directory}
#ACME_CA_URI="https://acme-staging.api.letsencrypt.org/directory"
LETSENCRYPT_EMAIL="wyatt.mike@gmail.com"

for host in "${HOSTS[@]}"; do
  certdir="/etc/nginx/certs/${host}"
  mkdir -p "${certdir}"
  (
    cd "${certdir}" || exit 1
    echo "Generating certs for ${host} ..." | /app/log
    simp_le \
        -f account_key.json -f key.pem -f fullchain.pem \
        -d "${host}" \
        --email "${LETSENCRYPT_EMAIL}" \
        --server "${ACME_CA_URI}" \
        --default_root /usr/share/nginx/html/
  )

  if [ $? -eq 0 ]; then
    reload_nginx="true"
    ln -sf "${certdir}/fullchain.pem" "/etc/nginx/certs/${host}.crt"
    ln -sf "${certdir}/key.pem" "/etc/nginx/certs/${host}.key"
    if [ -f /etc/nginx/certs/dhparam.pem ]; then
      ln -sf /etc/nginx/certs/dhparam.pem "/etc/nginx/certs/${host}.dhparam.pem"
    fi
  fi
done

if [ -n "${reload_nginx}" ]; then
  /app/gen-nginx-conf
  /app/copy-nginx-config
else
  echo "No new certs, skipping reload of ${NGINX_CONTAINER}" | /app/log
fi
